spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/product_service?authSource=admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
